// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LNHpOmbNb8JCveReU73b_HzLwMVl7vs',
    appId: '1:739297025304:web:b0d05537f63007d4fad26d',
    messagingSenderId: '739297025304',
    projectId: 'my-musichat-app',
    authDomain: 'my-musichat-app.firebaseapp.com',
    storageBucket: 'my-musichat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBkhBzrnPOqdcMmXYac_LKgzt17KAzuk',
    appId: '1:739297025304:android:282c3f716afef08ffad26d',
    messagingSenderId: '739297025304',
    projectId: 'my-musichat-app',
    storageBucket: 'my-musichat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FHP-89KxYB_MMI1EB5OJq7dATBD5vWE',
    appId: '1:739297025304:ios:a35c0c97e8776673fad26d',
    messagingSenderId: '739297025304',
    projectId: 'my-musichat-app',
    storageBucket: 'my-musichat-app.firebasestorage.app',
    iosBundleId: 'com.example.musichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FHP-89KxYB_MMI1EB5OJq7dATBD5vWE',
    appId: '1:739297025304:ios:a35c0c97e8776673fad26d',
    messagingSenderId: '739297025304',
    projectId: 'my-musichat-app',
    storageBucket: 'my-musichat-app.firebasestorage.app',
    iosBundleId: 'com.example.musichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4LNHpOmbNb8JCveReU73b_HzLwMVl7vs',
    appId: '1:739297025304:web:0e2ad816a7853370fad26d',
    messagingSenderId: '739297025304',
    projectId: 'my-musichat-app',
    authDomain: 'my-musichat-app.firebaseapp.com',
    storageBucket: 'my-musichat-app.firebasestorage.app',
  );
}
